name: stat_edu_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  url_launcher_platform_interface: ^2.3.2
  dartz: ^0.10.1
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^29.1.35
  dotted_line: ^3.2.3
  shimmer: ^3.0.0
  flutter_phone_direct_caller: ^2.2.1
  http: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: sfbold
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF

    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf