import 'package:stat_edu_mobile/sources.dart';

String getTranslateWord({required BuildContext context,required String value}){
  Map<String,String> values = {
    "Bakalavr": AppLocalizations.of(context)!.bachelor,
    "Magistr": AppLocalizations.of(context)!.masters,
    "Ordinatura": AppLocalizations.of(context)!.ordinatura,
    "Universitet":AppLocalizations.of(context)!.university,
    "Institut" : AppLocalizations.of(context)!.institute,
    "Filial": AppLocalizations.of(context)!.branch,
    "Akademiya": AppLocalizations.of(context)!.academy,
    "1-kurs":AppLocalizations.of(context)!.firstCourse,
    "2-kurs":AppLocalizations.of(context)!.secondCourse,
    "3-kurs": AppLocalizations.of(context)!.thirdCourse,
    "4-kurs": AppLocalizations.of(context)!.fourthCourse,
    "5-kurs": AppLocalizations.of(context)!.fifthCourse,
    "6-kurs": AppLocalizations.of(context)!.sixthCourse,
    "7-kurs": AppLocalizations.of(context)!.seventhCourse,
    "Davlat granti": AppLocalizations.of(context)!.stateGrant,
    "To'lov kontrakti": AppLocalizations.of(context)!.contractBased,
    "Sirtqi": AppLocalizations.of(context)!.external,
    "Qo'shma": AppLocalizations.of(context)!.joint,
    "Qo‘shma (sirtqi)": AppLocalizations.of(context)!.jointExternal,
    "Qo‘shma (kunduzgi)": AppLocalizations.of(context)!.jointDaytime,
    "Maxsus sirtqi": AppLocalizations.of(context)!.specialExternal,
    "Masofaviy": AppLocalizations.of(context)!.remote,
    "Kunduzgi":AppLocalizations.of(context)!.daytime,
    "Kechki": AppLocalizations.of(context)!.evening,
    "Ikkinchi oliy(sirtqi)": AppLocalizations.of(context)!.secondHigherExternal,
    "Ikkinchi oliy(kechki)": AppLocalizations.of(context)!.secondHigherEvening,
    "Ikkinchi oliy(kunduzgi)": AppLocalizations.of(context)!.secondHigherDaytime,
    "Ikkinchi oliy (sirtqi)": AppLocalizations.of(context)!.secondHigherExternal,
    "Ikkinchi oliy (kechki)": AppLocalizations.of(context)!.secondHigherEvening,
    "Ikkinchi oliy (kunduzgi)": AppLocalizations.of(context)!.secondHigherDaytime,
    "Andijon viloyati": AppLocalizations.of(context)!.andijanRegion,
    "Buxoro viloyati": AppLocalizations.of(context)!.bukharaRegion,
    "Farg‘ona viloyati":AppLocalizations.of(context)!.ferganaRegion,
    "Jizzax viloyati": AppLocalizations.of(context)!.jizzakhRegion,
    "Surxondaryo viloyati": AppLocalizations.of(context)!.surxondaryoRegion,
    "Sirdaryo viloyati": AppLocalizations.of(context)!.sirdaryoRegion,
    "Namangan viloyati": AppLocalizations.of(context)!.namanganRegion,
    "Navoiy viloyati": AppLocalizations.of(context)!.navoiyRegion,
    "Qashqadaryo viloyati": AppLocalizations.of(context)!.qashqadaryaRegion,
    "Qoraqalpog‘iston Resp.": AppLocalizations.of(context)!.karakalpakstan,
    "Samarqand viloyati": AppLocalizations.of(context)!.samarkandRegion,
    "Toshkent shahri":AppLocalizations.of(context)!.tashkentCity,
    "Toshkent viloyati": AppLocalizations.of(context)!.tashkentRegion,
    "Xorazm viloyati":AppLocalizations.of(context)!.khorezmRegion,
    "Toshkent davlat iqtisodiyot universiteti": AppLocalizations.of(context)!.economicsUniversity,
    "Toshkent Kimyo xalqaro universiteti": AppLocalizations.of(context)!.chemistryUniversity,
    "O‘zbekiston Milliy universiteti": AppLocalizations.of(context)!.nationalUniversity,
    "ISFT instituti": AppLocalizations.of(context)!.isftInstitute,
    "Farg‘ona davlat universiteti": AppLocalizations.of(context)!.ferganaUniversity,
    "Erkak": AppLocalizations.of(context)!.male,
    "Ayol": AppLocalizations.of(context)!.female,
    "30 yoshdan oshgan": AppLocalizations.of(context)!.above30,
    "30 yoshdan kichik": AppLocalizations.of(context)!.below30,
    "Fuqaroligi yo‘q shaxslar": AppLocalizations.of(context)!.noCitizenship,
    "O‘zbekiston Respublikasi fuqarosi": AppLocalizations.of(context)!.uzbekCitizen,
    "Xorijiy davlat fuqarosi" : AppLocalizations.of(context)!.foreignCitizen,
    "Dekan" : AppLocalizations.of(context)!.dean,
    "Kafedra mudiri": AppLocalizations.of(context)!.departmentHead,
    "Rector": AppLocalizations.of(context)!.rector,
    "Darajasiz": AppLocalizations.of(context)!.noDegree,
    "Darajali": AppLocalizations.of(context)!.hasDegree,
    "Fan doktori, DSc": AppLocalizations.of(context)!.dsc,
    "Fan nomzodi, PhD": AppLocalizations.of(context)!.phd,
    "Dotsent": AppLocalizations.of(context)!.docent,
    "Katta ilmiy xodim": AppLocalizations.of(context)!.seniorResearcher,
    "Professor": AppLocalizations.of(context)!.professor,
    "Unvonsiz":AppLocalizations.of(context)!.noTitle,
    "Assistent": AppLocalizations.of(context)!.assistant,
    "Katta o‘qituvchi" : AppLocalizations.of(context)!.seniorLecturer,
    "Stajer-o‘qituvchi" : AppLocalizations.of(context)!.traineeTeacher,
    "Asosiy ish joy": AppLocalizations.of(context)!.mainWorkPlace,
    "60 yoshdan yuqori" : AppLocalizations.of(context)!.ageAbove60,
    "55-60 yosh": AppLocalizations.of(context)!.age55_60,
    "50-55 yosh": AppLocalizations.of(context)!.age50_55,
    "45-50 yosh": AppLocalizations.of(context)!.age45_50,
    "40-45 yosh": AppLocalizations.of(context)!.age40_45,
    "35-40 yosh": AppLocalizations.of(context)!.age35_40,
    "30-35 yosh": AppLocalizations.of(context)!.age30_35,
    "30 yoshgacha": AppLocalizations.of(context)!.ageUnder30,
    "Nodavlat": AppLocalizations.of(context)!.nonGovernmental,
    "Davlat": AppLocalizations.of(context)!.governmental,
    "Xorijiy": AppLocalizations.of(context)!.foreign,
    "Ijaradagi uyda": AppLocalizations.of(context)!.rentedHouse,
    "O‘z uyida": AppLocalizations.of(context)!.ownHouse,
    "Qarindoshining uyida": AppLocalizations.of(context)!.relativeHouse,
    "Talabalar turar joyida": AppLocalizations.of(context)!.dormitory,
    "Tanishining uyida": AppLocalizations.of(context)!.friendHouse,
    "Kasb-hunar maktablari": AppLocalizations.of(context)!.vocationalSchool,
    "Kollejlar": AppLocalizations.of(context)!.colleges,
    "Voyaga yetmagan shaxslar": AppLocalizations.of(context)!.under18,
    "Boshqa": AppLocalizations.of(context)!.other,
    "Texnikumlar": AppLocalizations.of(context)!.technicalSchools,
    "Dual": AppLocalizations.of(context)!.dual,
    "20 yoshdan kichik": AppLocalizations.of(context)!.under20,
    "20 yoshdan katta": AppLocalizations.of(context)!.above20,
    "Erkaklar": AppLocalizations.of(context)!.men,
    "Ayollar": AppLocalizations.of(context)!.women,
    "Yotoqxonada": AppLocalizations.of(context)!.hostel,
    "To‘lov-shartnoma": AppLocalizations.of(context)!.contractBased,
    "20 yoshdan kichiklar": AppLocalizations.of(context)!.unders20,
    "20 yoshdan kattalar": AppLocalizations.of(context)!.overs20,
    "To'lov-kontrakt": AppLocalizations.of(context)!.contractBased,
    "Fuqaroligi yo‘q shaxs": AppLocalizations.of(context)!.noCitizenship,
    "Voyaga yetmagan shaxs": AppLocalizations.of(context)!.under18,
    "Kollej": AppLocalizations.of(context)!.college,
    "Texnikum": AppLocalizations.of(context)!.technicalSchool,
    "Kasb-hunar maktabi": AppLocalizations.of(context)!.vocationalSchool,
    "Qoraqalpog‘iston Respublikasi": AppLocalizations.of(context)!.karakalpakstan,
    "Jami": AppLocalizations.of(context)!.total,
    "Ta'lim turi": AppLocalizations.of(context)!.educationType,
    "Ta'lim shakli": AppLocalizations.of(context)!.educationForm,
    "To'lov shakli": AppLocalizations.of(context)!.paymentForm,
    "Fuqaroligi": AppLocalizations.of(context)!.citizenship,
    "Kurslar":AppLocalizations.of(context)!.courses,
    "Yoshi": AppLocalizations.of(context)!.age,
    "Yashash hududi": AppLocalizations.of(context)!.residenceRegion,
    "Hududlar kesimida": AppLocalizations.of(context)!.byRegions,
    "Mulkchilik shakli": AppLocalizations.of(context)!.ownership_form
  };

  if(values[value] == null){
    // print("diqqat mana bu so'z tarjimasi yoq $value");
  }

  return values[value] != null ? values[value]! : value;
}